#!/usr/bin/env python3
"""Merge bib/<chapter>.bib files into bib/thesis.bib, deduplicating by entry key.

First occurrence of a key wins; if a later file redefines the same key with
*different* content, a warning is printed (so genuine conflicts can be
inspected by hand) but the first definition is kept.

Usage: python3 tools/merge_bibs.py
"""
import re
import sys
from pathlib import Path

BIB_DIR = Path(__file__).resolve().parent.parent / "bib"
# Merge order: earlier files win on key conflicts.
SOURCES = [
    "intro.bib",
    "market-rl.bib", "agency.bib", "infonomy.bib", "solib.bib",
    "nonvf.bib", "consistency.bib",
]
OUT = BIB_DIR / "thesis.bib"

ENTRY_RE = re.compile(r"@(\w+)\s*[{(]\s*([^,\s]+)\s*,", re.IGNORECASE)


def split_entries(text: str):
    """Yield (kind, key, raw) for each @entry in the file, brace-balanced."""
    i = 0
    n = len(text)
    while i < n:
        at = text.find("@", i)
        if at == -1:
            return
        m = ENTRY_RE.match(text, at)
        if not m:
            i = at + 1
            continue
        kind = m.group(1).lower()
        # Balance only the delimiter the entry actually opens with; a '('-
        # delimited entry is closed by ')' but '{'-entries ignore parens
        # entirely (they occur freely inside field values).
        brace = text.find("{", at)
        paren = text.find("(", at)
        if brace != -1 and (paren == -1 or brace < paren):
            open_c, close_c = "{", "}"
            j = brace
        else:
            open_c, close_c = "(", ")"
            j = paren
        depth = 0
        while j < n:
            c = text[j]
            if c == open_c:
                depth += 1
            elif c == close_c:
                depth -= 1
                if depth == 0:
                    break
            j += 1
        raw = text[at : j + 1]
        yield kind, m.group(2), raw
        i = j + 1


def main() -> int:
    seen: dict[str, str] = {}
    order: list[str] = []
    strings: list[str] = []
    for name in SOURCES:
        path = BIB_DIR / name
        if not path.exists():
            print(f"[merge_bibs] missing {path}, skipping", file=sys.stderr)
            continue
        text = path.read_text(errors="replace")
        for kind, key, raw in split_entries(text):
            if kind in ("comment", "preamble"):
                continue
            if kind == "string":
                if raw not in strings:
                    strings.append(raw)
                continue
            if key in seen:
                if re.sub(r"\s+", "", seen[key]) != re.sub(r"\s+", "", raw):
                    print(f"[merge_bibs] WARNING: key '{key}' redefined differently "
                          f"in {name}; keeping first definition", file=sys.stderr)
                continue
            seen[key] = raw
            order.append(key)
    with OUT.open("w") as f:
        f.write("% Auto-generated by tools/merge_bibs.py -- do not edit by hand.\n"
                "% Edit the per-chapter bib/<chapter>.bib files and re-run the script.\n\n")
        for s in strings:
            f.write(s + "\n")
        for key in order:
            f.write(seen[key] + "\n\n")
    print(f"[merge_bibs] wrote {len(order)} entries to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
